import type { SupabaseClient } from "@supabase/supabase-js";

/**
 * Escape hatch for tables that aren't in the generated `Database` type yet.
 *
 * `types/database.ts` is generated by `npm run types` against the live schema,
 * so a table stays unknown to TypeScript until that runs somewhere the
 * migration has been applied. Rather than scatter `as any` through the call
 * sites, funnel it through one named, documented function — and delete this
 * once the types are regenerated.
 */
export function untyped(client: unknown): SupabaseClient {
  return client as SupabaseClient;
}
